apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-3
    app.kubernetes.io/part-of: test-app2
  name: java-quarkus-3
  namespace: christianvogt
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-quarkus-3
    weight: 100
status: {}
